# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-07 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user_key', models.CharField(max_length=200, unique=True, verbose_name='User Key')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='전화번호')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='성별')),
            ],
            options={
                'verbose_name': '친구',
                'verbose_name_plural': '친구',
            },
        ),
        migrations.AddField(
            model_name='youareuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='youareuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='youareuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
