# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-11 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180511_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='이름'),
        ),
    ]
