# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-19 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_friends_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('unique_key', models.CharField(max_length=200, unique=True, verbose_name='Device 고유키')),
                ('is_active', models.BooleanField(default=True, verbose_name='유효')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': '기기 정보',
                'verbose_name': '기기 정보',
            },
        ),
    ]
